### ISSUE TITLE
Feature Requests: add script to generate `compile_commands.json` to do code navigation using clangd

### ISSUE THREAD

**Issue by tedli** [merbridge/merbridge#109]
IDE for programming languages like Golang or Java, provides convenient code navigation features, and many programmers heavily rely on it.

Some C/C++ projects like [envoy](https://github.com/envoyproxy/envoy) provides scripts to generate `compile_commands.json`, so that we can use `clangd` to achieve code navigation like other languages do.

This can help reducing the learning curve of bpf codes in this project, and willing to do further contribution.

**Comment by kebe7jun** [comment]
Thanks. @tedli
