### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yulng** [merbridge/merbridge#124]
Description

1 Istio cluster：10.31.203.1
2 run commond:
kubectl apply -f https://raw.githubusercontent.com/merbridge/merbridge/main/deploy/all-in-one.yaml
3 
![wecom-temp-3e43ca41d2674afcec5919860a744722](https://user-images.githubusercontent.com/31728060/164212246-7a046b55-625f-420d-9f85-5e5ae5164534.png)

4 
![wecom-temp-d65dd8a67be8d78e2c0d08338e70a158](https://user-images.githubusercontent.com/31728060/164212343-e597288b-f0fa-49b4-9cc4-a8dd5f21eeb7.png)

### Version

```prose
5.11.8-1.el7.elrepo.x86_64

[root@master-node-1 home]# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by kebe7jun** [comment]
can you plz upload the merbridge pods' log?
currently, we did not test merbridge on centos...

maybe cgroupv2 not enabled.

**Comment by yulng** [comment]
yes,it is
![image](https://user-images.githubusercontent.com/31728060/164357333-3d3b6aad-9464-4eab-98d7-d79c47fe6b2b.png)

**Comment by kebe7jun** [comment]
enable cgroupv2 manually is ok.
