### ISSUE TITLE
Please provide the OS version number that meets the kernel version requirements

### ISSUE THREAD

**Issue by yulng** [merbridge/merbridge#127]
###  Description

The Ubuntu version found may not meet the kernel requirements, so please provide the available OS version number or version link

### Version

```prose
https://blog.csdn.net/weixin_40161232/article/details/85251250
```

**Comment by kebe7jun** [comment]
You can upgrade your kernel version manually.
eg:
```
sudo apt install linux-modules-5.11xxxx linux-image-5.11xxx linux-headers-5.11xxxx # 5.11xxxx is the version
```

and reboot your system.

or https://vitux.com/how-to-install-latest-linux-kernel-5-15-on-ubuntu-20-04/
