### ISSUE TITLE
shell script still need the license description

### ISSUE THREAD

**Issue by yulng** [merbridge/merbridge#130]
### Description

shell script still need the license description
such as:
![image](https://user-images.githubusercontent.com/31728060/164583281-e25e630e-3adf-4e38-98bb-86b2ef1d5b41.png)

[merbridge](https://github.com/merbridge/merbridge)/scripts/

### Version

```prose
shell script still need the license description
```

**Comment by Xunzhuo** [comment]
I will add it later, thanks.
