### ISSUE TITLE
Question: The sidecar injection policy when use ebpf.

### ISSUE THREAD

**Issue by zackzhangkai** [merbridge/merbridge#133]
### Bug Description

Not a bug, just a question.

As we know, when using ebpf , the node would be an node proxy. So all the pods in the node would be proxed. Is it?

### Version

```prose
Nothing
```

**Comment by kebe7jun** [comment]
Although eBPF works in a node-agent-like mode, our program determines whether the Pod is injected with Sidecar, and if it is not, then we don't do anything with it.
