### ISSUE TITLE
"run local ip controller error: load failed:

### ISSUE THREAD

**Issue by dyipon** [merbridge/merbridge#144]
### Bug Description

I just tried to install latest merbridge on debian hosted nodes, but gave the next error:

<img width="1877" alt="image" src="https://user-images.githubusercontent.com/35313394/166719532-394cf5a2-497e-4e66-a77e-65eb5d3481e6.png">

Any idea how can I fix it?

### Version

```prose
5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
```

**Comment by Xunzhuo** [comment]
I did not dig into the logs, but is it related to the recent cni works? cc @kebe7jun

**Comment by kebe7jun** [comment]
can you add an env to daemonset:
```
- name: CGROUP2_PATH
   value: /sys/fs/cgroup
```

This is caused by the mount command outputting multiple results, I will fix it.

https://github.com/merbridge/merbridge/blob/06a3cd9afd14f7777fef964330673ef051e18aab/bpf/Makefile#L50-L51

**Comment by dddddai** [comment]
> This should be caused by mounting the host path to the container.

Yeah I think so, but we have to mount the host path(`/var/run`), any thoughts?
