### ISSUE TITLE
have you considered cross-node scenarios?

### ISSUE THREAD

**Issue by withlin** [merbridge/merbridge#15]
as title

**Comment by kebe7jun** [comment]
Yes, we will gradually find reliable solutions to do some cross-node acceleration optimization later.

**Comment by withlin** [comment]
@kebe7jun  have you wechat group? which discuss for merbridge ?

**Comment by kebe7jun** [comment]
Now you can join the [Merbridge Slack](https://join.slack.com/t/merbridge/shared_invite/zt-11uc3z0w7-DMyv42eQ6s5YUxO5mZ5hwQ).
