### ISSUE TITLE
【Merbridge performance test  produces many errors】

### ISSUE THREAD

**Issue by tanjunchen** [merbridge/merbridge#172]
### Bug Description

【question】
```
   pilot-agent-69571   [006] d... 270197.943731: bpf_trace_printk: [debug] get current pod ip error
     pilot-agent-69571   [006] d... 270197.943738: bpf_trace_printk: [debug] call from sidecar container: cookie: 780438927, ip: 0xa9fcf8ac, port: 8080
     pilot-agent-91591   [030] d... 270198.324635: bpf_trace_printk: [debug] get current pod ip error
     pilot-agent-91591   [030] d... 270198.324643: bpf_trace_printk: [debug] call from sidecar container: cookie: 780424679, ip: 0xaffcf8ac, port: 8080
     pilot-agent-93300   [023] d... 270198.968152: bpf_trace_printk: [debug] get current pod ip error
     pilot-agent-93300   [023] d... 270198.968160: bpf_trace_printk: [debug] call from sidecar container: cookie: 780603512, ip: 0x88fcf8ac, port: 8080
     pilot-agent-4007    [031] d... 270199.160107: bpf_trace_printk: [debug] get current pod ip error
     pilot-agent-4007    [031] d... 270199.160116: bpf_trace_printk: [debug] call from sidecar container: cookie: 780349765, ip: 0x90fcf8ac, port: 8080
     pilot-agent-93217   [007] d... 270200.129528: bpf_trace_printk: [debug] get current pod ip error
     pilot-agent-93217   [007] d... 270200.129535: bpf_trace_printk: [debug] call from sidecar container: cookie: 780508501, ip: 0xbafcf8ac, port: 8080
     pilot-agent-3763    [017] d... 270201.118915: bpf_trace_printk: [debug] get current pod ip error
     pilot-agent-3763    [017] d... 270201.118924: bpf_trace_printk: [debug] call from sidecar container: cookie: 780646392, ip: 0xaafcf8ac, port: 8080
     pilot-agent-94600   [038] d... 270201.803920: bpf_trace_printk: [debug] get current pod ip error
           <...>-94887   [034] d... 270201.803927: bpf_trace_printk: [debug] get current pod ip error
```

【Kubernetes Cluster】

<div data-slate-node="element" class="mp-table-container" style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); margin: 1px 0px; overflow: auto hidden; padding-bottom: 8px; padding-top: 32px; position: relative; padding-left: 0px;">

os| Kernel | cpu |  memory
-- | -- | -- | --
 UOS | 5.10.0-10.uelc20.x86_64 | 40 | 256
 UOS | 5.10.0-10.uelc20.x86_64 | 40 | 256
 UOS | 5.10.0-10.uelc20.x86_64 | 40 | 256

</div><div class="mp-table-serialize-flag" style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0);"><br style="box-sizing: border-box; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); color: rgb(51, 51, 51); font-family: &quot;PingFang SC&quot;, &quot;Helvetica Neue&quot;, &quot;Hiragino Sans GB&quot;, &quot;Microsoft YaHei&quot;, Arial, SimSun, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(245, 245, 245); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

【Test Process】

1. deploy merbridge with cni  on.
2. use [load-tool](https://github.com/istio/tools/tree/master/perf/load ) to test merbridge. note: We access backend services through ingress-gateway. see [ingress-gateway](https://github.com/istio/tools/blob/master/perf/load/common.sh#L19). see 
![image](https://user-images.githubusercontent.com/19339970/174423488-f2cca990-5310-4a0e-856c-c0c623c9d315.png)
3. run test script.
4. there are so many error,see below logs.

### Version

```prose
Kubernetes Version：v1.19.15
kubectl Version：v1.19.15
istio Version：1.11.5
net plugin：   calico/kube-controllers:v3.20.1
Kernel Version:             5.10.0-10.uelc20.x86_64
OS Image:                   UnionTech OS Server 20
Operating System:           linux
Architecture:               amd64
Container Runtime Version:  docker://20.10.8
Kubelet Version:            v1.19.15
Kube-Proxy Version:         v1.19.15
```
```

**Comment by kebe7jun** [comment]
I will try to reproduce the problem as soon as possible and give you feedback later.

**Comment by tanjunchen** [comment]
> I will try to reproduce the problem as soon as possible and give you feedback later.

how is it？

**Comment by kebe7jun** [comment]
ohh, I'm very sorry for forgetting to reply. I tested this specifically a few days ago, and your problem did not reproduce in my environment. Can this be reproduced directly in your environment?

**Comment by tanjunchen** [comment]
> ohh, I'm very sorry for forgetting to reply. I tested this specifically a few days ago, and your problem did not reproduce in my environment. Can this be reproduced directly in your environment?

ok  i tested it again.

**Comment by kebe7jun** [comment]
Hi @tanjunchen , in the latest version, we have optimized the performance, can you test it again?

**Comment by tanjunchen** [comment]
@kebe7jun  hello I test it again，I have the same question. When the concurrency is high, merbridge will generate an error.
```
time="2023-04-20T10:15:35Z" level=error msg="init tc prog filed: field Ingress: program mb_tc_ingress: load program: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)" func="ebpfs.GetTCIngressProg()" file="prog.go:88"
time="2023-04-20T10:15:35Z" level=error msg="attach tc for eth0 of /host/proc/52817/ns/net error: can not get ingress prog" func="cni-server.(*server).checkAndRepairPodPrograms.func1()" file="cni-plugin.go:274"
time="2023-04-20T10:15:35Z" level=error msg="Failed to check existing pods: can not get ingress prog" func="cni-server.(*server).Start()" file="server.go:142"
time="2023-04-20T10:20:00Z" level=error msg="init tc prog filed: field Ingress: program mb_tc_ingress: load program: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)" func="ebpfs.GetTCIngressProg()" file="prog.go:88"
time="2023-04-20T10:20:00Z" level=error msg="CmdAdd failed for /var/run/netns/cni-2245ab6d-38b4-05df-b8f4-2fe378965ab0: can not get ingress prog" func="cni-server.(*server).CmdAdd()" file="cni-plugin.go:107"
time="2023-04-20T10:20:00Z" level=error msg="merbridge-cni cmdAdd error: can not get ingress prog" func="cni-server.(*server).CmdAdd.func1()" file="cni-plugin.go:75"
time="2023-04-20T10:30:00Z" level=error msg="init tc prog filed: field Ingress: program mb_tc_ingress: load program: operation not permitted (MEMLOCK may be too low, consider rlimit.RemoveMemlock)" func="ebpfs.GetTCIngressProg()" file="prog.go:88"
time="2023-04-20T10:30:00Z" level=error msg="CmdAdd failed for /var/run/netns/cni-4e98c1bf-f7a1-7e75-371d-50288b8bedac: can not get ingress prog" func="cni-server.(*server).CmdAdd()" file="cni-plugin.go:107"
```

**Comment by kebe7jun** [comment]
This should be the result of not executing RemoveMemLock in the code.
