### ISSUE TITLE
What is mb_get_sockopts.c used for? Don't understand

### ISSUE THREAD

**Issue by liuqi-sun** [merbridge/merbridge#189]
![image](https://user-images.githubusercontent.com/48784730/182113389-67f22829-28c8-4252-8f0f-d46bf1dbd025.png)
I don't understand the above description. After the Outbound traffic is hijacked to port 15001, the Outbound Handler routes it to the upstream cluster based on virtualHost. Why does EBPF need to obtain the original address?

The following is the Outbound Handler
![image](https://user-images.githubusercontent.com/48784730/182114171-f1655c79-9b48-4230-a8f3-e9e8d993ac55.png)

**Comment by kebe7jun** [comment]
Is was because the original dst, 
More info please visit: https://merbridge.io/blog/2022/03/01/merbridge-introduce/#processing-outbound-traffic
