### ISSUE TITLE
excludedInboundPort / excludedOutboundPort don't work fine with istio

### ISSUE THREAD

**Issue by jalonsoa** [merbridge/merbridge#277]
### Bug Description

Hi team !
  we have an elastic cluster installed with elastic operator inside a kubernetes cluster with istio and merbridge. Elastic need direct connection in the transport layer because have client/servcer certificate authentication (certificates managed by operator). So we need add the istio annotations:

    traffic.sidecar.istio.io/excludeInboundPorts: "9300"
    traffic.sidecar.istio.io/excludeOutboundPorts: "9300"

  Well ... when elastic node try to connect to another nodes we hace errors with certificates. Debugging with curl/openssl inside the node we can see that if we have merbridge installed the other node don't present certificate (the tls connection don't works). If we uninstall merbridge then, all work fine.

  With merbridge installed:

```
# curl -sik --verbose https://10.116.64.70:9300
* Rebuilt URL to: https://10.116.64.70:9300/
*   Trying 10.116.64.70...
* TCP_NODELAY set
* Connected to 10.116.64.70 (127.128.2.165) port 9300 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to 10.116.64.70:9300 
* Closing connection 0
```
without merbridge:
```
# curl -sik --verbose https://10.116.64.70:9300
* Rebuilt URL to: https://10.116.64.70:9300/
*   Trying 10.116.64.70...
* TCP_NODELAY set
* Connected to 10.116.64.70 (10.116.64.70) port 9300 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Request CERT (13):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: OU=elastic-cluster; CN=elastic-cluster-es-elasticsearch-1.node.elastic-cluster.demo.es.local
*  start date: Mar  8 18:07:52 2023 GMT
*  expire date: Mar  7 18:17:52 2024 GMT
*  issuer: OU=extended-assortment-api; CN=elastic-clusteri-transport
*  SSL certificate verify result: self signed certificate in certificate chain (19), continuing anyway.
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET / HTTP/1.1
> Host: 10.116.64.70:9300
> User-Agent: curl/7.61.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS alert, [no content] (0):
* TLSv1.3 (IN), TLS alert, bad certificate (554):
* OpenSSL SSL_read: error:14094412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate, errno 0
* Closing connection 0
```

### Version

```prose
# uname -a
Linux gke-cluster-name-default-pool-9a811024-6870 5.10.162+ #1 SMP Thu Jan 26 15:59:51 UTC 2023 x86_64 AMD EPYC 7B12 AuthenticAMD GNU/Linux

# cat /etc/os-release
NAME="Container-Optimized OS"
ID=cos
PRETTY_NAME="Container-Optimized OS from Google"
HOME_URL="https://cloud.google.com/container-optimized-os/docs"
BUG_REPORT_URL="https://cloud.google.com/container-optimized-os/docs/resources/support-policy#contact_us"
KERNEL_COMMIT_ID=3db1b2d6a249eff0e52d0964503af751941088d3
GOOGLE_METRICS_PRODUCT_ID=26
GOOGLE_CRASH_ID=Lakitu
VERSION=97
VERSION_ID=97
BUILD_ID=16919.235.9

$ ./bin/istioctl version --remote
client version: 1.16.2
control plane version: 1.16.2
data plane version: 1.16.2 (218 proxies)
```

**Comment by kebe7jun** [comment]
Do you have cni mode turned on?

**Comment by jalonsoa** [comment]
No,
  istio cni mode is disabled

**Comment by kebe7jun** [comment]
istio annotations (like `traffic.sidecar.istio.io/excludeInboundPorts `) requires cni mode~
you can try to enable it.

**Comment by jalonsoa** [comment]
Hi kebe7jun !
   thanks for your answers. I don't known about this "limitation". We can't use cni mode because we have init-containers that need network connection (and dns resolution).

  Can you add the cni requirement to the merbridge documentation ?

thanks !

**Comment by kebe7jun** [comment]
I developed ambient mode can not open cni mode, you can try ~ 
https://github.com/merbridge/merbridge/blob/ambient/deploy/all-in-one.yaml

Currently for testing purposes only~

I look forward to your feedback!

**Comment by jalonsoa** [comment]
Hi,
   but the merbridge is not changing the "connection path":

* Connected to 10.116.68.100 (10.116.68.100) port 9200 (#0)

  How works ambient ? if the pod have istio annotations then disable the ebpf connection ?

  Im tying with other pods and all connection are by iptables ... so .. don't works .. no ?

**Comment by kebe7jun** [comment]
> if the pod have istio annotations then disable the ebpf connection ?

Yes!

> Im tying with other pods and all connection are by iptables ... so .. don't works .. no ?

Merbridge works in compatibility mode by default, you can try going into the pod's netns and disabling iptables to see the effect of Merbridge~ Or you can just look at the real link address of `curl -v` (by Service name).

**Comment by jalonsoa** [comment]
All is working fine ... we will report any issue about this !
