### ISSUE TITLE
【Advice】Merbridge Performance Testing and Design Document

### ISSUE THREAD

**Issue by tanjunchen** [merbridge/merbridge#303]
It is recommended to give the merbridge performance test plan and data in the repo or official website.
With the performance test plan and data, design plan and other things, 
the confidence of merbridge production and use can be improved

【Performance Tool】
see https://github.com/istio/tools/blob/master/perf/README.md

**Comment by kebe7jun** [comment]
Very excited, we are considering doing continuous performance testing and are currently researching, any suggestions can be made and we will do it together.
We have obtained the infrastructure from CNCF to do continuous performance testing.
