### ISSUE TITLE
My query is how does it prove that it speeds up things?

### ISSUE THREAD

**Issue by AshwinRamaniPsg** [merbridge/merbridge#43]
### Bug Description

My query is how does it prove that it speeds up things?

### Version

```prose
My query is how does it prove that it speeds up things?
```

**Comment by kebe7jun** [comment]
I'm writing a blog about how Merbridge works, and I'll give you the link when I do.

**Comment by AshwinRamaniPsg** [comment]
Thanks please point me to the blog once done

**Comment by kebe7jun** [comment]
@AshwinRamaniPsg The blog was posted to istio, see: https://istio.io/latest/blog/2022/merbridge/
