### ISSUE TITLE
Use helm instead of pure yaml

### ISSUE THREAD

**Issue by kebe7jun** [merbridge/merbridge#57]

**Comment by Kodalien** [comment]
can you let me try @kebe7jun  Please assign to me if you can

**Comment by kebe7jun** [comment]
wow, of course!

**Comment by kebe7jun** [comment]
Some tasks:
- [ ] Add helm charts in deploy.
- [ ] Auto generate pure yaml to `all-in-one.*.yaml` by `helm template` cmd.
- [ ] CI: Auto check pure yamls matched with `helm template` cmd.
