### ISSUE TITLE
Istio can exclude some ips or ports by iptables, can this support?

### ISSUE THREAD

**Issue by zhengzepeng** [merbridge/merbridge#99]
istio can exclude some ip or port by iptables, can this support?

**Comment by kebe7jun** [comment]
yes, it is in our ROADMAP.

See: https://github.com/merbridge/merbridge/blob/main/ROADMAP.md#control-plane

`Istio sidecar annotions`

We may impl it in the next two months.

**Comment by zhengzepeng** [comment]
> yes, it is in our ROADMAP.
> 
> See: https://github.com/merbridge/merbridge/blob/main/ROADMAP.md#control-plane
> 
> `Istio sidecar annotions`
> 
> We may impl it in the next two months.

thx~
